import XCTest
@testable import Spool

/// Replays fixtures/engine-parity.json (generated by the TypeScript
/// reference via `npm run fixtures:engine`) against the Swift
/// implementation. A failure here means the two platforms have diverged —
/// fix the Swift side, or if the TS change was intentional, port it.
final class EngineParityTests: XCTestCase {

    // MARK: fixture schema

    struct Corpus: Decodable {
        let constants: Constants
        let cases: [Case]
    }
    struct Constants: Decodable {
        let tierScoreRanges: [String: Range]
        let newUserThreshold: Int
    }
    struct Range: Decodable { let min: Double; let max: Double }
    struct Case: Decodable {
        let name: String
        let tier: String
        let newItem: Item
        let allItems: [TierItem]
        let choices: [String]
        let expectedSteps: [Step]
        let expectedFinalRank: Int
        let expectedFinalScore: Double?
    }
    struct Item: Decodable { let id: String; let title: String; let genres: [String]; let globalScore: Double? }
    struct TierItem: Decodable { let id: String; let title: String; let genres: [String]; let tier: String; let rank: Int; let globalScore: Double? }
    struct Step: Decodable { let round: Int; let phase: String; let movieBId: String }

    // MARK: helpers

    private func loadCorpus() throws -> Corpus {
        // …/ios/Spool/Tests/SpoolTests/EngineParityTests.swift → repo root is 5 hops up
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // SpoolTests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // Spool
            .deletingLastPathComponent()  // ios
            .deletingLastPathComponent()  // repo root
        let url = repoRoot.appendingPathComponent("fixtures/engine-parity.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Corpus.self, from: data)
    }

    private func tier(_ raw: String) -> Tier {
        guard let t = Tier(rawValue: raw) else {
            XCTFail("unknown tier raw value \(raw)"); return .D
        }
        return t
    }

    private func ranked(_ it: TierItem) -> RankedItem {
        RankedItem(id: it.id, title: it.title, genres: it.genres,
                   tier: tier(it.tier), rank: it.rank, globalScore: it.globalScore)
    }

    // MARK: tests

    func testConstantsMatchFixture() throws {
        let corpus = try loadCorpus()
        XCTAssertEqual(corpus.constants.newUserThreshold, SpoolConstants.newUserThreshold)
        for (raw, range) in corpus.constants.tierScoreRanges {
            let t = tier(raw)
            XCTAssertEqual(t.scoreRange.min, range.min, accuracy: 0.0001, "\(raw).min")
            XCTAssertEqual(t.scoreRange.max, range.max, accuracy: 0.0001, "\(raw).max")
        }
    }

    func testReplayAllCases() throws {
        let corpus = try loadCorpus()
        for c in corpus.cases {
            let allItems = c.allItems.map(ranked)
            let newItem = RankedItem(
                id: c.newItem.id, title: c.newItem.title, genres: c.newItem.genres,
                tier: tier(c.tier), rank: 0, globalScore: c.newItem.globalScore
            )
            let session = PlacementSession()
            var result = session.start(newItem: newItem, tier: tier(c.tier), allItems: allItems)
            var stepIdx = 0

            loop: while true {
                switch result {
                case .comparison(let comp):
                    guard stepIdx < c.expectedSteps.count else {
                        XCTFail("\(c.name): more comparisons than expected"); break loop
                    }
                    let want = c.expectedSteps[stepIdx]
                    XCTAssertEqual(comp.round, want.round, "\(c.name) step \(stepIdx) round")
                    XCTAssertEqual(comp.phase.rawValue, want.phase, "\(c.name) step \(stepIdx) phase")
                    XCTAssertEqual(comp.movieB.id, want.movieBId, "\(c.name) step \(stepIdx) movieB")

                    let choice = c.choices[stepIdx]
                    stepIdx += 1
                    let next: EngineResult?
                    switch choice {
                    case "new":      next = session.submit(winnerId: newItem.id)
                    case "existing": next = session.submit(winnerId: comp.movieB.id)
                    case "skip":     next = session.skip()
                    default:
                        XCTFail("\(c.name): unknown choice \(choice)"); break loop
                    }
                    guard let n = next else {
                        XCTFail("\(c.name): session rejected choice \(choice) at step \(stepIdx)"); break loop
                    }
                    result = n

                case .done(let rank, let score):
                    XCTAssertEqual(stepIdx, c.expectedSteps.count, "\(c.name): step count")
                    XCTAssertEqual(rank, c.expectedFinalRank, "\(c.name): finalRank")
                    if let wantScore = c.expectedFinalScore {
                        XCTAssertEqual(score, wantScore, accuracy: 0.0001, "\(c.name): finalScore")
                    }
                    break loop
                }
            }
        }
    }
}
